## 서비스 설정
server:
  port: ${HOST_PORT:10234}
  # kill -15 : 정상 종료
  # kill -9 : 강제 종료
  shutdown: graceful

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/interior?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

feign:
  target-api:
    kakao-nlp: ${API_URL}

tag:
  # custom / kakao
  type: custom