# OpenAPI Swagger setting
springdoc:
  api-docs:
    groups:
      enabled: true
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    # Swagger-UI 활성화
    enabled: true
    # swagger-ui custom path
    #    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    tagsSorter: alpha
    display-query-params-without-oauth2: true
  group-configs:
    - group: contact
      paths-to-match: /api/v1/contact/**
    - group: interior
      paths-to-match: /api/v1/interior/**
